#!/bin/bash

WD=`pwd`
PKG='PACKAGES.txt'
PPA='PPA.txt'
VIM='vim/'
TMUX='tmux/'
CONFIGS='configs/'
GITCONFIG=$CONFIGS'gitconfig'
ALIAS=$CONFIGS'bash_aliases'

## Functions

clean() {
    echo "Reverting changes"

    if [[ -d "~/.vim" ]]; then
        rm -rf ~/.vim
        rm ~/.vimrc
    fi

    if [[ -d "~/.tmux" ]]; then
        rm -rf ~/.tmux
        rm ~/.tmux.conf
    fi

    if [[ -f "~/.gitconfig" ]]; then
        rm ~/.gitconfig
    fi

    if [[ -f "~/.bash_aliases" ]]; then
        rm ~/.bash_aliases
    fi
}

clean_packages() {
    while read -r line; do
        pkg="$line"
        sudo apt-get remove $pkg -y
        sudo apt-get purge $pkg -y
    done < "$PKG"
}



setup_vim() {
    cd $WD
    cd vim
    bash install.sh install
}

setup_tmux() {
    cd $WD
    cp -av $TMUX ~/.tmux
    cd ~/.tmux
    echo "Choose OS :"
    echo -e "\t1. Ubuntu\n\t2. Ubuntu - Powerline\n\t3. MacOS"
    read version

    case "$version" in
        1)
            bash install.sh ubuntu
            ;;
        2)
            bash install.sh powerline
            ;;
        3)
            bash install.sh mac
            ;;
        *)
            echo "Invalid option chosen"
            cleanup
            exit 1
    esac
}

setup_git_config() {
    flag=1
    cd $WD
    cp $GITCONFIG ~/.gitconfig

    read -p "Enter name for Git config : " name
    sed -i 's/John Doe/'"${name}"'/g' ~/.gitconfig

    read -p "Enter email for Git config : " email
    sed -i 's/johndoe@test.com/'"${email}"'/g' ~/.gitconfig
}

setup_bash_aliases() {
    cd $WD
    cp $ALIAS ~/.bash_aliases
    source ~/.bashrc
}

install_nodejs() {
    VERSION=v16.13.1
    DISTRO=linux-x64
    wget -P /tmp https://nodejs.org/dist/${VERSION}/node-${VERSION}-${DISTRO}.tar.xz
    sudo mkdir -p /usr/local/lib/nodejs
    sudo tar -xJvf /tmp/node-$VERSION-$DISTRO.tar.xz -C /usr/local/lib/nodejs
    rm /tmp/node-$VERSION-$DISTRO.tar.xz

    echo "export PATH=/usr/local/lib/nodejs/node-$VERSION-$DISTRO/bin:$PATH" >> ~/.bash_aliases
    source ~/.bash_aliases
}

setup_packages() {
    cd $WD
    sudo apt-get install software-properties-common -y
    while read -r line; do
        ppa="$line"
        sudo add-apt-repository ppa:$ppa -y
    done < "$PPA"

    install_nodejs

    sudo apt-get update
    while read -r line; do
        pkg="$line"
        sudo apt-get install $pkg -y
    done < "$PKG"
}

main() {
    clean
    if [[ $EUID -eq 0 ]]; then
        setup_packages
    else
        setup_bash_aliases
        setup_git_config
        setup_tmux
        setup_vim
    fi
    cd $WD
}

# Call the main function
main
