#!/bin/bash

echo "Uninstalling linux-environtment-setup"


if [[ -d "~/.vim" ]]; then
    rm -rf ~/.vim
    rm ~/.vimrc
fi

if [[ -d "~/.tmux" ]]; then
    rm -rf ~/.tmux
    rm ~/.tmux.conf
fi

if [[ -f "~/.gitconfig" ]]; then
    rm ~/.gitconfig
fi

if [[ -f "~/.bash_aliases" ]]; then
    rm ~/.bash_aliases
fi

if [[ -d "~/.config/nvim" ]]; then
    rm -rf ~/.config/nvim
fi

while read -r line; do
    pkg="$line"
    sudo apt-get remove $pkg -y
    sudo apt-get purge $pkg -y
done < "$PKG"
