#!/bin/bash

DOCUMENTS=$HOME/Documents
DOWNLOADS=$HOME/Downloads
DESKTOP=$HOME/Desktop
TOOLS=$HOME/Tools
PSU=$HOME/PSU-MS-Computer-Science
FALL19=$PSU/FALL19
SPRING20=$PSU/SPRING20
DBMS=$FALL19/COMP519
AI=$FALL19/COMP520
ALGO_BS=$FALL19/CMPSC463
ALGO=$SPRING20/COMP511
OS=$SPRING20/COMP512
APL=$SPRING20/COMP516
WEBSITE=$PSU/public_html
RA=$PSU/RA
MACHINES=$HOME/Machines
UBUNTU1604=$MACHINES/ubuntu-1604
WIN10=$MACHINES/win-10
BOXES=$MACHINES/Boxes
PROJECTS=$HOME/Projects


## Aliases

# Protect against stupidity
alias rm='rm -I'

# Git Aliases
alias gic='git clean -fdx'
alias gib='git branch'
alias gibd='git branch -D'
alias gid='git diff'
alias gidc='git diff --cached'
alias gil='git log --decorate --graph'
alias gila='git log --decorate --pretty=format:"%h [%an][%ad] %s" --graph'
alias gilp='git log --decorate --patch --graph'
alias gils='git log --decorate --stat --graph'
alias gis='git status'
alias gir='git reset'
alias girh='git reset --hard @{u}'
alias gip='git pull'
alias gipr='git pull --rebase'
alias giri='git rebase --interactive HEAD~'

# Command Aliases
alias torrent='utserver -settingspath /opt/utorrent-server-alpha-v3_3/'
alias sshag='eval $(ssh-agent)'
alias sshad='ssh-add '$HOME'/.ssh/github'
alias ghkey='sshag sshad'
alias pymol=$HOME'/Softwares/pymol/pymol > /dev/null &'
alias rmtags='rm cscope.* tags'
alias tags='rmtags; find . -name "*.c" -o -name "*.cpp" -o -name "*.hpp" -o -name "*.h" -o -name "*.go" -o -name "*.py" > cscope.files; cscope -b; rm cscope.files; ctags -R --exclude=*.js'
alias vagrant=$TOOLS'/vagrant/vagrant'
alias vim-help='cat ~/.vim/doc/help.txt'

# Directory Aliases
alias dbms='cd $DBMS'
alias ai='cd $AI'
alias algo_bs='cd $ALGO_BS'
alias algo='cd $ALGO'
alias os='cd $OS'
alias apl='cd $APL'
alias ra='cd $RA'
alias tools='cd $TOOLS'
alias docs='cd $DOCUMENTS'
alias dl='cd $DOWNLOADS'
alias psu='cd $PSU'
alias vms='cd $MACHINES'
alias ubuntu='cd $UBUNTU1604'
alias win10='cd $WIN10'
alias boxes='cd $BOXES'
alias proj='cd $PROJECTS'
alias mlproj='cd $PROJECTS/comp520'

# SSH Aliases
alias 122s1='ssh ps122s1@euler.hbg.psu.edu -t bash'
alias 122s2='ssh ps122s2@euler.hbg.psu.edu -t bash'
alias euler='ssh vmp5265@euler.hbg.psu.edu'
alias dahl='ssh vmp5265@dahl.hbg.psu.edu'
alias ada='ssh vmp5265@ada.hbg.psu.edu'
alias erdos='ssh vmp5265@erdos.hbg.psu.edu'
alias yeuler='ssh -Y vmp5265@euler.hbg.psu.edu'
alias ydahl='ssh -Y vmp5265@dahl.hbg.psu.edu'
alias yada='ssh -Y vmp5265@ada.hbg.psu.edu'
alias yerdos='ssh -Y vmp5265@erdos.hbg.psu.edu'

# Custom Functions
function search {
    if [ $# -lt 1 ]; then
        echo "Usage : search <file|text> [OPTIONS]"
        echo "      OPTIONS"
        echo "          file : <directory> <pattern>"
        echo "          text : [directory] <pattern>"
        return
    fi

    case "$1" in
        file)
            if [ $# -eq 3 ] && [ -d $2 ]; then
                find $2 -name $3
            else
                echo "Usage : search file <directory> <pattern>";
            fi
            ;;
        text)
            if [ $# -eq 2 ] && ! [ -d $2 ]; then
                grep -rnw -e $2;
            elif [ $# -eq 3 ] && [ -d $2 ]; then
                grep -rnw $1 -e $2;
            else
                echo "Usage : search text [directory] <pattern>";
            fi
            ;;
        *)
            echo $1
            echo "Usage : search <file|text> [OPTIONS]"
            echo "      OPTIONS"
            echo "          file : <directory> <pattern>"
            echo "          text : [directory] <pattern>"
            ;;
    esac
}

function course {
    if [[ $# -lt 2 ]]; then
        echo "Usage : course <course> <data> [data-value]"
        exit 1
    fi

    course=${1^^}
    data=$2
    data_value=$3

    case $2 in
        book)
            cd ${!course}/Book
            ;;
        hw)
            if [[ -z "$data_value" ]]; then
                cd ${!course}/Homeworks
            else
                cd ${!course}/Homeworks/Assignment${data_value}
            fi
            ;;
        latex)
            cd ${!course}/Latex
            ;;
        *)
            cd ${!course}
            ;;
    esac
}

function runscm {
    if [[ $# -lt 1 ]]; then
        echo "Usage : runscm <file>"
        exit 1
    fi

    scheme --quiet < "$1"
}

export GIT_EDITOR=vim
export EDITOR=vim
export VISUAL=vim
export -f search
export -f course
export -f runscm
