#!/bin/bash

DOCUMENTS=$HOME/Documents
DOWNLOADS=$HOME/Downloads
DESKTOP=$HOME/Desktop
TOOLS=$HOME/Tools
MACHINES=$HOME/Machines
PROJECTS=$HOME/Projects


## Aliases

# Protect against stupidity
alias rm='rm -I'

# Git Aliases
alias gic='git clean -fdx'
alias gib='git branch'
alias gibd='git branch -D'
alias gid='git diff'
alias gids='git diff --stat'
alias gidc='git diff --cached'
alias gil='git log --decorate --graph'
alias gila='git log --decorate --pretty=format:"%h [%an][%ad] %s" --graph'
alias gilp='git log --decorate --patch --graph'
alias gils='git log --decorate --stat --graph'
alias gis='git status'
alias gir='git reset'
alias girh='git reset --hard @{u}'
alias gip='git pull'
alias gipr='git pull --rebase'
alias giri='git rebase --interactive HEAD~'

# Command Aliases
alias sshag='eval $(ssh-agent)'
alias ghkey='sshag ssh-add ~/.ssh/github'
alias rmtags='rm cscope.*'
alias tags='rmtags; find . -name "*.c" -o -name "*.cpp" -o -name "*.hpp" -o -name "*.cc" -o -name "*.hh" -o -name "*.h" -o -name "*.go" -o -name "*.py" > cscope.files; cscope -b; rm cscope.files;'
alias vim-help='cat ~/.vim/doc/help.txt'

# Directory Aliases
alias tools='cd $TOOLS'
alias docs='cd $DOCUMENTS'
alias dl='cd $DOWNLOADS'
alias vms='cd $MACHINES'
alias proj='cd $PROJECTS'

# SSH Aliases

function call_graph {
    if [[ $# -ne 3 ]]; then
        echo "Usage : call_graph <rtl_file> <caller_func> <img_name>"
        exit 1
    fi

    rtl_file=$1
    caller_fn=$2
    img_file=$3

    cally.py ${rtl_file} --no-extern -e "__.*|cJSON.*|.*encoded_sz" --caller ${caller_fn} | dot -Grankdir=LR -Tpng -o ${img_file}
}

# Terminal Prompt
git_branch() {
    git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

PS1="\[\e[0;93m\]\u\[\e[m\]"    # username
PS1+=" "    # space
PS1+="\[\e[0;95m\]\w\[\e[m\]"    # current directory
PS1+="\[\e[0;92m\]\$(git_branch)\[\e[m\]"    # current branch
PS1+=" "    # space
PS1+="$ "    # end prompt

export PS1;

export GIT_EDITOR=vim
export EDITOR=vim
export VISUAL=vim
export -f call_graph
