#!/bin/bash

DOCUMENTS=$HOME/Documents
DOWNLOADS=$HOME/Downloads
DESKTOP=$HOME/Desktop

## Aliases

# Protect against stupidity
alias rm='rm -I'

# Git Aliases
alias gic='git clean -fdx'
alias gib='git branch'
alias gibd='git branch -D'
alias gid='git diff'
alias gids='git diff --stat'
alias gidc='git diff --cached'
alias gil='git log --decorate --graph'
alias gila='git log --decorate --pretty=format:"%h [%an][%ad] %s" --graph'
alias gilp='git log --decorate --patch --graph'
alias gils='git log --decorate --stat --graph'
alias gis='git status'
alias gir='git reset'
alias girh='git reset --hard @{u}'
alias gip='git pull'
alias gipr='git pull --rebase'
alias giri='git rebase --interactive HEAD~'

# Command Aliases
alias sshag='eval $(ssh-agent)'
alias sshad='ssh-add '$HOME'/.ssh/github'
alias ghkey='sshag sshad'
alias rmtags='rm cscope.* tags'
alias tags='rmtags; find . -name "*.c" -o -name "*.cpp" -o -name "*.hpp" -o -name "*.cc" -o -name "*.hh" -o -name "*.h" -o -name "*.go" -o -name "*.py" > cscope.files; cscope -b; rm cscope.files; ctags -R --exclude=*.js'
alias vim-help='cat ~/.vim/doc/help.txt'

# Directory Aliases
alias docs='cd $DOCUMENTS'
alias dl='cd $DOWNLOADS'

# Custom Functions
function search {
    if [ $# -lt 1 ]; then
        echo "Usage : search <file|text> [OPTIONS]"
        echo "      OPTIONS"
        echo "          file : <directory> <pattern>"
        echo "          text : [directory] <pattern>"
        return
    fi

    case "$1" in
        file)
            if [ $# -eq 3 ] && [ -d $2 ]; then
                find $2 -name $3
            else
                echo "Usage : search file <directory> <pattern>";
            fi
            ;;
        text)
            if [ $# -eq 2 ] && ! [ -d $2 ]; then
                grep -rnw -e $2;
            elif [ $# -eq 3 ] && [ -d $2 ]; then
                grep -rnw $1 -e $2;
            else
                echo "Usage : search text [directory] <pattern>";
            fi
            ;;
        *)
            echo $1
            echo "Usage : search <file|text> [OPTIONS]"
            echo "      OPTIONS"
            echo "          file : <directory> <pattern>"
            echo "          text : [directory] <pattern>"
            ;;
    esac
}

git_branch() {
    git branch 2>/dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

PS1="\[\e[0;93m\]\u\[\e[m\]"    # username
PS1+=" "    # space
PS1+="\[\e[0;95m\]\w\[\e[m\]"    # current directory
PS1+="\[\e[0;92m\]\$(git_branch)\[\e[m\]"    # current branch
PS1+=" "    # space
PS1+="$ "    # end prompt

export PS1;
export GIT_EDITOR=vim
export EDITOR=vim
export VISUAL=vim
export -f search
